# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui',
# licensing of 'ui/main.ui' applies.
#
# Created: Wed Apr 29 21:36:23 2020
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setStyleSheet("QGroupBox{\n"
"  border: none;\n"
"  margin-top: 2ex;\n"
"}\n"
" QGroupBox::title{\n"
"  subcontrol-origin: \n"
"  margin;subcontrol-position:\n"
"  top left;\n"
"  margin-left: 5px;\n"
"  padding:0px 3px;\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_10.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cmbReader = QtWidgets.QComboBox(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbReader.sizePolicy().hasHeightForWidth())
        self.cmbReader.setSizePolicy(sizePolicy)
        self.cmbReader.setMinimumSize(QtCore.QSize(200, 0))
        self.cmbReader.setObjectName("cmbReader")
        self.horizontalLayout_10.addWidget(self.cmbReader)
        self.btnReloadReader = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReloadReader.sizePolicy().hasHeightForWidth())
        self.btnReloadReader.setSizePolicy(sizePolicy)
        self.btnReloadReader.setMinimumSize(QtCore.QSize(100, 0))
        self.btnReloadReader.setObjectName("btnReloadReader")
        self.horizontalLayout_10.addWidget(self.btnReloadReader)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setStyleSheet("QGroupBox{\n"
"  border: none;\n"
"  margin-top: 2ex;\n"
"}\n"
" QGroupBox::title{\n"
"  subcontrol-origin: \n"
"  margin;subcontrol-position:\n"
"  top left;\n"
"  margin-left: 5px;\n"
"  padding:0px 3px;\n"
"}")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_13.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnConnetPICC = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConnetPICC.sizePolicy().hasHeightForWidth())
        self.btnConnetPICC.setSizePolicy(sizePolicy)
        self.btnConnetPICC.setMinimumSize(QtCore.QSize(100, 0))
        self.btnConnetPICC.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnConnetPICC.setObjectName("btnConnetPICC")
        self.horizontalLayout_13.addWidget(self.btnConnetPICC)
        self.horizontalLayout_3.addWidget(self.groupBox_9)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setStyleSheet("QGroupBox{\n"
"  border: none;\n"
"  margin-top: 2ex;\n"
"}\n"
" QGroupBox::title{\n"
"  subcontrol-origin: \n"
"  margin;subcontrol-position:\n"
"  top left;\n"
"  margin-left: 5px;\n"
"  padding:0px 3px;\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_11.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.txtUID = QtWidgets.QLineEdit(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtUID.sizePolicy().hasHeightForWidth())
        self.txtUID.setSizePolicy(sizePolicy)
        self.txtUID.setMinimumSize(QtCore.QSize(50, 0))
        self.txtUID.setReadOnly(True)
        self.txtUID.setObjectName("txtUID")
        self.horizontalLayout_11.addWidget(self.txtUID)
        self.horizontalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setStyleSheet("QGroupBox{\n"
"  border: none;\n"
"  margin-top: 2ex;\n"
"}\n"
" QGroupBox::title{\n"
"  subcontrol-origin: \n"
"  margin;subcontrol-position:\n"
"  top left;\n"
"  margin-left: 5px;\n"
"  padding:0px 3px;\n"
"}")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_12.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.txtATR = QtWidgets.QLineEdit(self.groupBox_8)
        self.txtATR.setMinimumSize(QtCore.QSize(200, 0))
        self.txtATR.setReadOnly(True)
        self.txtATR.setObjectName("txtATR")
        self.horizontalLayout_12.addWidget(self.txtATR)
        self.horizontalLayout_3.addWidget(self.groupBox_8)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.frame_2)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(9, 9, 720, 150))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txtKeyA0 = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyA0.sizePolicy().hasHeightForWidth())
        self.txtKeyA0.setSizePolicy(sizePolicy)
        self.txtKeyA0.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyA0.setMaxLength(2)
        self.txtKeyA0.setObjectName("txtKeyA0")
        self.horizontalLayout_5.addWidget(self.txtKeyA0)
        self.txtKeyA1 = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyA1.sizePolicy().hasHeightForWidth())
        self.txtKeyA1.setSizePolicy(sizePolicy)
        self.txtKeyA1.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyA1.setMaxLength(2)
        self.txtKeyA1.setObjectName("txtKeyA1")
        self.horizontalLayout_5.addWidget(self.txtKeyA1)
        self.txtKeyA2 = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyA2.sizePolicy().hasHeightForWidth())
        self.txtKeyA2.setSizePolicy(sizePolicy)
        self.txtKeyA2.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyA2.setMaxLength(2)
        self.txtKeyA2.setObjectName("txtKeyA2")
        self.horizontalLayout_5.addWidget(self.txtKeyA2)
        self.txtKeyA3 = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyA3.sizePolicy().hasHeightForWidth())
        self.txtKeyA3.setSizePolicy(sizePolicy)
        self.txtKeyA3.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyA3.setMaxLength(2)
        self.txtKeyA3.setObjectName("txtKeyA3")
        self.horizontalLayout_5.addWidget(self.txtKeyA3)
        self.txtKeyA4 = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyA4.sizePolicy().hasHeightForWidth())
        self.txtKeyA4.setSizePolicy(sizePolicy)
        self.txtKeyA4.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyA4.setMaxLength(2)
        self.txtKeyA4.setObjectName("txtKeyA4")
        self.horizontalLayout_5.addWidget(self.txtKeyA4)
        self.txtKeyA5 = QtWidgets.QLineEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyA5.sizePolicy().hasHeightForWidth())
        self.txtKeyA5.setSizePolicy(sizePolicy)
        self.txtKeyA5.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyA5.setMaxLength(2)
        self.txtKeyA5.setObjectName("txtKeyA5")
        self.horizontalLayout_5.addWidget(self.txtKeyA5)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnAuthKeyA = QtWidgets.QPushButton(self.frame_4)
        self.btnAuthKeyA.setObjectName("btnAuthKeyA")
        self.horizontalLayout_6.addWidget(self.btnAuthKeyA)
        self.btnFactoryKeyA = QtWidgets.QPushButton(self.frame_4)
        self.btnFactoryKeyA.setObjectName("btnFactoryKeyA")
        self.horizontalLayout_6.addWidget(self.btnFactoryKeyA)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.txtKeyB0 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyB0.sizePolicy().hasHeightForWidth())
        self.txtKeyB0.setSizePolicy(sizePolicy)
        self.txtKeyB0.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyB0.setMaxLength(2)
        self.txtKeyB0.setObjectName("txtKeyB0")
        self.horizontalLayout_7.addWidget(self.txtKeyB0)
        self.txtKeyB1 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyB1.sizePolicy().hasHeightForWidth())
        self.txtKeyB1.setSizePolicy(sizePolicy)
        self.txtKeyB1.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyB1.setMaxLength(2)
        self.txtKeyB1.setObjectName("txtKeyB1")
        self.horizontalLayout_7.addWidget(self.txtKeyB1)
        self.txtKeyB2 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyB2.sizePolicy().hasHeightForWidth())
        self.txtKeyB2.setSizePolicy(sizePolicy)
        self.txtKeyB2.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyB2.setMaxLength(2)
        self.txtKeyB2.setObjectName("txtKeyB2")
        self.horizontalLayout_7.addWidget(self.txtKeyB2)
        self.txtKeyB3 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyB3.sizePolicy().hasHeightForWidth())
        self.txtKeyB3.setSizePolicy(sizePolicy)
        self.txtKeyB3.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyB3.setMaxLength(2)
        self.txtKeyB3.setObjectName("txtKeyB3")
        self.horizontalLayout_7.addWidget(self.txtKeyB3)
        self.txtKeyB4 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyB4.sizePolicy().hasHeightForWidth())
        self.txtKeyB4.setSizePolicy(sizePolicy)
        self.txtKeyB4.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyB4.setMaxLength(2)
        self.txtKeyB4.setObjectName("txtKeyB4")
        self.horizontalLayout_7.addWidget(self.txtKeyB4)
        self.txtKeyB5 = QtWidgets.QLineEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKeyB5.sizePolicy().hasHeightForWidth())
        self.txtKeyB5.setSizePolicy(sizePolicy)
        self.txtKeyB5.setMaximumSize(QtCore.QSize(30, 30))
        self.txtKeyB5.setMaxLength(2)
        self.txtKeyB5.setObjectName("txtKeyB5")
        self.horizontalLayout_7.addWidget(self.txtKeyB5)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btnAuthKeyB = QtWidgets.QPushButton(self.frame_6)
        self.btnAuthKeyB.setObjectName("btnAuthKeyB")
        self.horizontalLayout_8.addWidget(self.btnAuthKeyB)
        self.btnFactoryKeyB = QtWidgets.QPushButton(self.frame_6)
        self.btnFactoryKeyB.setObjectName("btnFactoryKeyB")
        self.horizontalLayout_8.addWidget(self.btnFactoryKeyB)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.horizontalLayout_4.addWidget(self.groupBox_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.tableView = QtWidgets.QTableView(self.tab_2)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 913, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "PCC", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("MainWindow", "Reader", None, -1))
        self.btnReloadReader.setText(QtWidgets.QApplication.translate("MainWindow", "Reload", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "PICC", None, -1))
        self.btnConnetPICC.setText(QtWidgets.QApplication.translate("MainWindow", "Connect", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("MainWindow", "UID", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("MainWindow", "ATR", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "Select", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Block", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Sector", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("MainWindow", "Key A", None, -1))
        self.txtKeyA0.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyA1.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyA2.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyA3.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyA4.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyA5.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.btnAuthKeyA.setText(QtWidgets.QApplication.translate("MainWindow", "Authenticate", None, -1))
        self.btnFactoryKeyA.setText(QtWidgets.QApplication.translate("MainWindow", "Factory", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("MainWindow", "Key B", None, -1))
        self.txtKeyB0.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyB1.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyB2.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyB3.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyB4.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.txtKeyB5.setText(QtWidgets.QApplication.translate("MainWindow", "FF", None, -1))
        self.btnAuthKeyB.setText(QtWidgets.QApplication.translate("MainWindow", "Authenticate", None, -1))
        self.btnFactoryKeyB.setText(QtWidgets.QApplication.translate("MainWindow", "Factory", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Operations", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtWidgets.QApplication.translate("MainWindow", "Utility", None, -1))

